version: '3'

services:
  python-app:
    build:
      context: ../../
      dockerfile: ./.devcontainer/initial/Dockerfile
    image: my-devcontainer-app:latest
    command: sleep infinity
    volumes:
      - ../../:/app
